use_frameworks!

target 'QXArrangeView_Example' do
  pod 'QXArrangeView', :path => '../'

  target 'QXArrangeView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
